name: Tests
 
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Mise en cache des dépendances
      # - name: Get composer cache directory
      #   id: composer-cache
      #   run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ steps.composer-cache.outputs.dir }}
      #     key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: ${{ runner.os }}-composer-

      # - name: Install dependencies
      #   run: composer install --prefer-dist

      # Validation composer.json et composer.lock
      - name: Validation composer.json et composer.lock
        run: composer validate

      - uses: symfonycorp/security-checker-action@v2

      # Tests Unitaires
      - name: Tests Unitaires
        run: php bin/phpunit --testdox